package com.openrecords.api.domain;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.openrecords.api.util.BusinessDayCalculator;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * A FOIA (Freedom of Information Act) request. Mirrors the foia_requests table.
 *
 * Identity:
 *   - id is a database-generated UUID (see V3 migration: DEFAULT gen_random_uuid()).
 *   - tracking_number is a human-readable public identifier generated by the service layer
 *     on submission (e.g., "FOIA-2026-000001").
 *
 * State:
 *   - status represents where the request is in the workflow. See FoiaRequestStatus.
 *   - version powers JPA optimistic locking — prevents lost updates when staff members
 *     edit concurrently.
 */
@Entity
@Table(name = "foia_requests")
public class FoiaRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "tracking_number", nullable = false, unique = true, length = 20)
    private String trackingNumber;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignee_id")
    private User assignee;

    // --------- Ownership ---------
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "requester_id", nullable = false)
    private User requester;

    // --------- Request content ---------
    @Column(nullable = false)
    private String subject;

    @Column(nullable = false, columnDefinition = "text")
    private String description;

    @Column(name = "records_requested", nullable = false, columnDefinition = "text")
    private String recordsRequested;

    @Column(name = "date_range_start")
    private LocalDate dateRangeStart;

    @Column(name = "date_range_end")
    private LocalDate dateRangeEnd;

    // --------- Workflow state ---------
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private FoiaRequestStatus status = FoiaRequestStatus.DRAFT;

    // --------- Fee preferences ---------
    @Column(name = "fee_waiver_requested", nullable = false)
    private boolean feeWaiverRequested = false;

    @Column(name = "max_fee_willing", precision = 10, scale = 2)
    private BigDecimal maxFeeWilling;

    // --------- SLA timestamps ---------
    @Column(name = "submitted_at")
    private OffsetDateTime submittedAt;

    @Column(name = "acknowledged_at")
    private OffsetDateTime acknowledgedAt;

    @Column(name = "due_date")
    private LocalDate dueDate;

    @Column(name = "closed_at")
    private OffsetDateTime closedAt;

    // --------- Audit columns ---------
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @Version
    @Column(nullable = false)
    private Integer version;

    // ==============================
    // Constructors
    // ==============================
    protected FoiaRequest() {
        // JPA
    }

    public FoiaRequest(User requester, String trackingNumber, String subject,
                       String description, String recordsRequested) {
        this.requester = requester;
        this.trackingNumber = trackingNumber;
        this.subject = subject;
        this.description = description;
        this.recordsRequested = recordsRequested;
        this.status = FoiaRequestStatus.DRAFT;
    }

    // ==============================
    // Workflow mutator (used by service layer only)
    // ==============================

    /**
     * Apply a status transition AND update the relevant lifecycle timestamps.
     *
     * NOTE: This method does NOT validate the transition. The service layer
     * is responsible for calling FoiaRequestStatus.canTransitionTo() first.
     * Keeping the entity dumb about workflow rules lets the service own that logic
     * (and write audit history) atomically.
     */
    public void applyStatusChange(FoiaRequestStatus newStatus) {
        this.status = newStatus;

        OffsetDateTime now = OffsetDateTime.now();

        // Set lifecycle timestamps when entering specific states
        switch (newStatus) {
            case SUBMITTED -> {
                if (this.submittedAt == null) this.submittedAt = now;
            }
            case ACKNOWLEDGED -> {
                if (this.acknowledgedAt == null) {
                    this.acknowledgedAt = now;
                    // Federal FOIA SLA: 20 business days from acknowledgement (5 U.S.C. § 552(a)(6))
                    if (this.dueDate == null) {
                        this.dueDate = BusinessDayCalculator.addBusinessDays(
                            now.toLocalDate(), 20
                        );
                    }
                }
            }
            case CLOSED, REJECTED, DOCUMENTS_RELEASED, NO_RECORDS -> {
                if (this.closedAt == null) this.closedAt = now;
            }
            default -> {
                // No timestamp side effect for other states
            }
        }
    }

    // ==============================
    // Assignment mutators
    // ==============================

    /**
     * Assign this request to a staff user.
     * Caller is responsible for verifying the user has STAFF or ADMIN role.
     */
    public void assignTo(User staffUser) {
        this.assignee = staffUser;
    }

    /**
     * Clear the assignment.
     */
    public void unassign() {
        this.assignee = null;
    }

    // ==============================
    // Getters
    // ==============================
    public UUID getId() { return id; }
    public String getTrackingNumber() { return trackingNumber; }
    public User getRequester() { return requester; }
    public String getSubject() { return subject; }
    public String getDescription() { return description; }
    public String getRecordsRequested() { return recordsRequested; }
    public LocalDate getDateRangeStart() { return dateRangeStart; }
    public LocalDate getDateRangeEnd() { return dateRangeEnd; }
    public FoiaRequestStatus getStatus() { return status; }
    public boolean isFeeWaiverRequested() { return feeWaiverRequested; }
    public BigDecimal getMaxFeeWilling() { return maxFeeWilling; }
    public OffsetDateTime getSubmittedAt() { return submittedAt; }
    public OffsetDateTime getAcknowledgedAt() { return acknowledgedAt; }
    public LocalDate getDueDate() { return dueDate; }
    public OffsetDateTime getClosedAt() { return closedAt; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }
    public Integer getVersion() { return version; }
    public User getAssignee() { return assignee; }

    // ==============================
    // Setters for fields the requester can edit before submission
    // ==============================
    public void setSubject(String subject) { this.subject = subject; }
    public void setDescription(String description) { this.description = description; }
    public void setRecordsRequested(String recordsRequested) { this.recordsRequested = recordsRequested; }
    public void setDateRangeStart(LocalDate dateRangeStart) { this.dateRangeStart = dateRangeStart; }
    public void setDateRangeEnd(LocalDate dateRangeEnd) { this.dateRangeEnd = dateRangeEnd; }
    public void setFeeWaiverRequested(boolean feeWaiverRequested) { this.feeWaiverRequested = feeWaiverRequested; }
    public void setMaxFeeWilling(BigDecimal maxFeeWilling) { this.maxFeeWilling = maxFeeWilling; }
    public void setAssignee(User assignee) { this.assignee = assignee; }
}